export const canterAmArova = {
    card: true,
    border: true,
    selection: true,
    indexWidth: 70,
    searchLabelWidth: 120,
    labelWidth: 145,
    searchBtnText: "搜 索",
    searchMenuSpan: 6,
    searchSpan: 6,
    align: 'center',
    maxHeight: 480,
    menuWidth: 165,
    columnBtn: false,
    addBtn: false,
    editBtn: false,
    delBtn: false,
    size: 'mini',
    column: [{
        label: '卡类型',
        prop: 'cardTypeComplex',
        type: "select",
        dicUrl: '/center/basiccardtype/getCardTypeListByAsc',
        props: {
            label: 'typeName',
            value: 'cardTypeComplex'
        },
        disabled: true,
        width: 150,
        search: true,
        overHidden: true
    }, {
        label: '姓名',
        prop: 'cardOwnerName',
        disabled: true,
        search: true,
        overHidden: true
    }, {
        label: '证件类型',
        prop: 'idType',
        type: "select",
        disabled: true,
        dicData: [{
            label: '身份证',
            value: 1,
        }, {
            label: '护照',
            value: 2,
        }, {
            label: '学生证',
            value: 3,
        }, {
            label: '军官证',
            value: 4,
        }],
        width: 125,
        overHidden: true
    }, {
        label: '证件号码',
        prop: 'idNo',
        width: 220,
        disabled: true,
        slot: true,
        search: true,
        overHidden: true
    }, {
        label: '单位/地区',
        prop: 'unit',
        disabled: true,
        placeholder: ' ',
        span: 24,
        hide: true
    }, {
        label: '剩余金额',
        prop: 'cardMoney',
        width: 125,
        overHidden: true
    }, {
        label: '剩余次数',
        prop: 'cardTimes',
        width: 125,
        overHidden: true
    }, {
        label: '创建账户操作员',
        prop: 'createUserName',
        width: 185,
        overHidden: true
    }, {
        label: '账户创建时间',
        prop: 'issueTime',
        width: 165,
        overHidden: true
    }, {
        label: '年检有效期',
        prop: 'cardCheckDate',
        width: 125,
        overHidden: true
    }, {
        label: '账户状态',
        prop: 'cardStatus',
        type: 'select',
        width: 125,
        dicData: [{
            label: '正常启用',
            value: 1,
        }, {
            label: '未售',
            value: 0,
        }],
        overHidden: true
    }]
}