export const canterAmVaa = {
    card: true,
    border: true,
    index: true,
    indexLabel: '序号',
    indexWidth: 70,
    searchLabelWidth: 145,
    searchBtnText: "搜索",
    searchMenuSpan: 6,
    searchSpan: 6,
    align: 'center',
    maxHeight: 480,
    columnBtn: false,
    addBtn: false,
    editBtn: false,
    delBtn: false,
    size: 'mini',
    column: [{
        label: '卡类型',
        prop: 'typeName',
        search: true,
        overHidden: true
    }, {
        label: '姓名',
        prop: 'cardOwnerName',
        search: true,
        overHidden: true
    }, {
        label: '证件类型',
        prop: 'idType',
        width: 125,
        overHidden: true
    }, {
        label: '证件号码',
        prop: 'idCardNo',
        width: 175,
        search: true,
        overHidden: true
    }, {
        label: '介质',
        prop: 'sdasdsa',
        overHidden: true
    }, {
        label: '剩余金额',
        prop: 'asdasdasdas',
        width: 125,
        overHidden: true
    }, {
        label: '剩余次数',
        prop: 'sadasdasdasdas',
        width: 125,
        overHidden: true
    }, {
        label: '柜面操作员',
        prop: 'jfoskdofd',
        width: 125,
        overHidden: true
    }, {
        label: '账户创建日期',
        prop: 'jdfosdjpo',
        width: 125,
        search: true,
        overHidden: true
    }, {
        label: '账户有效期',
        prop: 'djfidshf8i',
        width: 220,
        overHidden: true
    }, {
        label: '审核状态',
        prop: 'orderReviewState',
        width: 125,
        search: true,
        overHidden: true
    }, {
        label: '审核人员',
        prop: 'kfopfkgfpdo',
        width: 125,
        overHidden: true
    }, {
        label: '审核时间',
        prop: 'reviewTime',
        width: 125,
        overHidden: true
    }, {
        label: '审核备注',
        prop: 'note',
        minWidth: 125,
        overHidden: true
    }]
}
