export const canterAmVaa = {
    card: true,
    border: true,
    selection: false,
    indexWidth: 70,
    searchLabelWidth: 145,
    labelWidth: 145,
    searchBtnText: "搜 索",
    searchMenuSpan: 8,
    searchSpan: 8,
    align: 'center',
    maxHeight: 480,
    menuWidth: 165,
    editTitle: '审核',
    updateBtnText: '保存审核结果',
    cancelBtnText: '取消返回',
    columnBtn: false,
    addBtn: false,
    editBtn: false,
    delBtn: false,
    size: 'mini',
    column: [{
        label: '卡类型',
        prop: 'cardTypeComplex',
        type: "select",
        dicUrl: '/center/basiccardtype/getCardTypeListByAsc',
        props: {
            label: 'typeName',
            value: 'cardTypeComplex'
        },
        disabled: true,
        width: 150,
        search: true,
        overHidden: true
    }, {
        label: '账户有效期',
        prop: 'cardCheckDate',
        disabled: true,
        width: 160,
        overHidden: true
    }, {
        label: '姓名',
        prop: 'cardOwnerName',
        disabled: true,
        search: true,
        overHidden: true
    }, {
        label: '联系方式',
        prop: 'tel',
        disabled: true,
        placeholder: ' ',
        hide: true
    }, {
        label: '证件类型',
        prop: 'idType',
        type: "select",
        disabled: true,
        dicData: [{
            label: '身份证',
            value: 1,
        }, {
            label: '护照',
            value: 2,
        }, {
            label: '学生证',
            value: 3,
        }, {
            label: '军官证',
            value: 4,
        }],
        width: 125,
        overHidden: true
    }, {
        label: '证件号码',
        prop: 'idNo',
        width: 220,
        disabled: true,
        search: true,
        overHidden: true
    }, /*{
    label: '剩余金额',
    prop: 'cardMoney',
    width: 125,
    search: true,
    overHidden: true
  }, {
    label: '剩余次数',
    prop: 'cardTimes',
    width: 125,
    search: true,
    overHidden: true
  }, */{
        label: '柜面操作员',
        prop: 'createUserName',
        width: 255,
        display: false,
        overHidden: true
    }, {
        label: '账户创建日期',
        prop: 'issueTime',
        type: "daterange",
        display: false,
        searchRange: true,
        width: 200,
        search: true,
        overHidden: true
    }, {
        label: '单位地区',
        prop: 'unit',
        disabled: true,
        placeholder: ' ',
        span: 24,
        hide: true
    }, {
        label: '地址',
        type: 'textarea',
        prop: 'address',
        disabled: true,
        placeholder: ' ',
        maxRows: 2,
        span: 24,
        hide: true
    }, {
        label: '审核状态',
        prop: 'vcardState',
        type: "select",
        formslot: true,
        dicData: [{
            label: '审核未通过',
            value: -1,
        }, {
            label: '审核通过',
            value: 1,
        }, {
            label: '未审核',
            value: 0,
        }],
        width: 125,
        search: true,
        overHidden: true
    }, {
        label: '审核人员',
        prop: 'operateUserName',
        display: false,
        width: 125,
        overHidden: true
    }, {
        label: '',// 支付介质
        prop: 'PaymentMedium',
        labelWidth: 0,
        span: 24,
        formslot: true,
        hide: true,
        overHidden: true
    }, {
        label: '审核时间',
        prop: 'operateTime',
        display: false,
        width: 125,
        overHidden: true
    }, {
        label: '审核备注',
        prop: 'operateNote',
        type: 'textarea',
        disabled: false,
        maxRows: 2,
        minWidth: 125,
        span: 24,
        overHidden: true
    }]
}
